// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDog8l-lRW1yS5SODMesY4XgmK-3w11GfE',
    appId: '1:320273808306:web:d7f303c26f337d5e9382ab',
    messagingSenderId: '320273808306',
    projectId: 'venti-f8985',
    authDomain: 'venti-f8985.firebaseapp.com',
    storageBucket: 'venti-f8985.appspot.com',
    measurementId: 'G-BNY299JBE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYuL7dSkLHdK7Bx9yawA2Xz-RS3W7UyBE',
    appId: '1:320273808306:android:d20266a00e1bbbc59382ab',
    messagingSenderId: '320273808306',
    projectId: 'venti-f8985',
    storageBucket: 'venti-f8985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLr2x2qrmNC8GMFo0ZSv8mfX9-B1O-hgQ',
    appId: '1:320273808306:ios:db86c01273342c419382ab',
    messagingSenderId: '320273808306',
    projectId: 'venti-f8985',
    storageBucket: 'venti-f8985.appspot.com',
    iosBundleId: 'com.example.venti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLr2x2qrmNC8GMFo0ZSv8mfX9-B1O-hgQ',
    appId: '1:320273808306:ios:60aba350ef06e5d79382ab',
    messagingSenderId: '320273808306',
    projectId: 'venti-f8985',
    storageBucket: 'venti-f8985.appspot.com',
    iosBundleId: 'com.example.venti.RunnerTests',
  );
}
